import { moduleMetaSchema, type ModuleMeta } from "@/lib/schemas/module";

/**
 * All 13 modules' architecture (routing, gating, unit grouping) exists here.
 * Live content today: module 1 (./01-this-years-challenge) and module 4
 * (./04-anatomy-of-a-rocket). Other modules render as "coming soon".
 * 1-indexed throughout, matching the live prototype and all user-facing copy.
 */
const raw: ModuleMeta[] = [
  {
    id: "this-years-challenge",
    slug: "this-years-challenge",
    order: 1,
    unit: 1,
    unitTitle: "Before you build",
    title: "This Year's Challenge",
    summary:
      "This season's flight goal, the parts of a competition rocket, and how a flight is scored.",
    estimatedMinutes: 22,
    readMinutes: 9,
    isTimeless: false,
    prerequisiteIds: [],
    ngssCodes: ["MS-ETS1-1", "MS-ETS1-2", "MS-PS2-2"],
    status: "live",
    needsReview: true,
    gradeBand: "6th–12th grade",
    objectives: [
      "State this year's flight goal precisely — altitude, duration, payload, and liftoff mass.",
      "Name the main parts of a competition rocket and explain what each one does.",
      "Explain how a flight is scored, and why altitude and duration both matter.",
    ],
  },
  {
    id: "what-you-signed-up-for",
    slug: "what-you-signed-up-for",
    order: 2,
    unit: 1,
    unitTitle: "Before you build",
    title: "What You Just Signed Up For",
    summary: "Season overview, team roles, and the time budget ahead.",
    estimatedMinutes: 11,
    isTimeless: true,
    prerequisiteIds: [],
    ngssCodes: ["MS-ETS1-1"],
    status: "soon",
    needsReview: true,
  },
  {
    id: "safety-first",
    slug: "safety-first",
    order: 3,
    unit: 1,
    unitTitle: "Before you build",
    title: "Safety First",
    summary: "The NAR Model Rocket Safety Code, supervision, and launch sites.",
    estimatedMinutes: 14,
    isTimeless: true,
    prerequisiteIds: [],
    ngssCodes: [],
    status: "soon",
    needsReview: true,
  },
  {
    id: "anatomy-of-a-rocket",
    slug: "anatomy-of-a-rocket",
    order: 4,
    unit: 2,
    unitTitle: "How rockets work",
    title: "Anatomy of a Rocket",
    summary:
      "Inner systems (motor, altimeter, chute, Nomex, egg case), outer airframe, and OpenRocket.",
    estimatedMinutes: 24,
    readMinutes: 12,
    isTimeless: true,
    prerequisiteIds: [],
    ngssCodes: ["MS-ETS1-2", "MS-PS2-1", "MS-PS2-2"],
    status: "live",
    needsReview: false,
    gradeBand: "6th–12th grade",
    objectives: [
      "Separate inner flight systems from outer airframe parts and explain what each does.",
      "Read a motor code (impulse class, thrust, delay) and name the three burn phases.",
      "State ARC constraints for motors, altimeters, cotton parachutes, and tube size.",
      "Explain how OpenRocket helps before build — and why practice flights still matter.",
    ],
  },
  {
    id: "why-rockets-fly-straight",
    slug: "why-rockets-fly-straight",
    order: 5,
    unit: 2,
    unitTitle: "How rockets work",
    title: "Why Rockets Fly Straight",
    summary: "Center of pressure, center of gravity, and stability margin.",
    estimatedMinutes: 16,
    isTimeless: true,
    prerequisiteIds: [],
    ngssCodes: ["MS-PS2-1", "MS-PS2-2"],
    status: "soon",
    needsReview: true,
  },
  {
    id: "thrust-impulse-and-motors",
    slug: "thrust-impulse-and-motors",
    order: 6,
    unit: 2,
    unitTitle: "How rockets work",
    title: "Thrust, Impulse, and Motors",
    summary: "Thrust curves, motor codes, and delay grains.",
    estimatedMinutes: 15,
    isTimeless: true,
    prerequisiteIds: [],
    ngssCodes: ["MS-PS2-1", "MS-PS2-2"],
    status: "soon",
    needsReview: true,
  },
  {
    id: "drag-and-altitude",
    slug: "drag-and-altitude",
    order: 7,
    unit: 2,
    unitTitle: "How rockets work",
    title: "Drag and Altitude",
    summary: "Why hitting the altitude target is hard.",
    estimatedMinutes: 13,
    isTimeless: true,
    prerequisiteIds: [],
    ngssCodes: ["MS-ETS1-2", "MS-PS2-1", "HS-PS2-1"],
    status: "soon",
    needsReview: true,
  },
  {
    id: "simulating-in-openrocket",
    slug: "simulating-in-openrocket",
    order: 8,
    unit: 3,
    unitTitle: "Design and build",
    title: "Simulating in OpenRocket",
    summary: "Building and reading a simulation.",
    estimatedMinutes: 22,
    isTimeless: true,
    prerequisiteIds: [],
    ngssCodes: [
      "MS-ETS1-2",
      "MS-ETS1-4",
      "HS-ETS1-2",
      "HS-ETS1-3",
      "HS-ETS1-4",
    ],
    status: "soon",
    needsReview: true,
  },
  {
    id: "building-it",
    slug: "building-it",
    order: 9,
    unit: 3,
    unitTitle: "Design and build",
    title: "Building It",
    summary: "Cutting, fillets, fin alignment, and motor retention.",
    estimatedMinutes: 26,
    isTimeless: true,
    prerequisiteIds: ["safety-first"],
    ngssCodes: ["HS-ETS1-2", "HS-ETS1-3"],
    status: "soon",
    needsReview: true,
  },
  {
    id: "recovery-and-the-egg",
    slug: "recovery-and-the-egg",
    order: 10,
    unit: 3,
    unitTitle: "Design and build",
    title: "Recovery and the Egg",
    summary: "Parachute sizing, descent rate, and packing.",
    estimatedMinutes: 18,
    isTimeless: true,
    prerequisiteIds: [],
    ngssCodes: [],
    status: "soon",
    needsReview: true,
  },
  {
    id: "launch-day",
    slug: "launch-day",
    order: 11,
    unit: 4,
    unitTitle: "Fly and qualify",
    title: "Launch Day",
    summary: "Pad setup, checklists, wind, and scrub criteria.",
    estimatedMinutes: 17,
    isTimeless: true,
    prerequisiteIds: ["safety-first"],
    ngssCodes: [],
    status: "soon",
    needsReview: true,
  },
  {
    id: "reading-a-flight-and-iterating",
    slug: "reading-a-flight-and-iterating",
    order: 12,
    unit: 4,
    unitTitle: "Fly and qualify",
    title: "Reading a Flight and Iterating",
    summary: "Altimeter data, and changing one variable at a time.",
    estimatedMinutes: 19,
    isTimeless: true,
    prerequisiteIds: [],
    ngssCodes: ["MS-ETS1-3"],
    status: "soon",
    needsReview: true,
  },
  {
    id: "qualification-and-beyond",
    slug: "qualification-and-beyond",
    order: 13,
    unit: 4,
    unitTitle: "Fly and qualify",
    title: "Qualification and Beyond",
    summary: "Observer rules, forms, and submission.",
    estimatedMinutes: 12,
    isTimeless: true,
    prerequisiteIds: [],
    ngssCodes: [],
    status: "soon",
    needsReview: true,
  },
];

export const MODULES: ModuleMeta[] = raw.map((m) => moduleMetaSchema.parse(m));

export const UNITS = Array.from(new Set(MODULES.map((m) => m.unit))).map(
  (unit) => ({
    unit,
    title: MODULES.find((m) => m.unit === unit)!.unitTitle,
    modules: MODULES.filter((m) => m.unit === unit),
  }),
);

export function getModuleBySlug(slug: string): ModuleMeta | undefined {
  return MODULES.find((m) => m.slug === slug);
}

export function getNextModule(currentOrder: number): ModuleMeta | undefined {
  return MODULES.find((m) => m.order === currentOrder + 1);
}
