/** Sources supplied by the user, with original primary references. Checked 2026-09-20. */
export const COURSE_RESOURCES = [
  {
    id: "2027-american-rocketry-challenge-rules",
    title: "2027 competition rules",
    group: "Start here",
    note: "Official requirements; use these for season rules.",
    href: "https://www.rocketrychallenge.org/wp-content/uploads/2027_AmericanRocketryChallenge_Rules.pdf",
  },
  {
    id: "2027-team-handbook",
    title: "2027 team handbook",
    group: "Start here",
    note: "Detailed guidance, safety code, and competition procedures.",
    href: "https://www.rocketrychallenge.org/wp-content/uploads/ARC2027_Handbook.pdf",
  },
  {
    id: "approved-motors-list",
    title: "2027 approved motors",
    group: "Design and build",
    note: "Check the exact motor, not just its letter class.",
    href: "https://www.rocketrychallenge.org/wp-content/uploads/Rocket-Motors-Approved-for-ARC-2027-6-Jul-2026.pdf",
  },
  {
    id: "arc-2027-parameters",
    title: "2027 targets at a glance",
    group: "Start here",
    note: "One-page season specifications.",
    href: "https://www.rocketrychallenge.org/wp-content/uploads/ARC2027_Parameters-1.pdf",
  },
  {
    id: "estes-education-american-rocketry-challenge-trainings-2023",
    title: "Estes training · 2023",
    group: "Watch a demonstration",
    note: "Archive: use for techniques, not current competition targets.",
    href: "https://www.rocketrychallenge.org/resource/estes-education-american-rocketry-challenge-trainings-2023/",
  },
  {
    id: "estes-education-american-rocketry-challenge-trainings-2024",
    title: "Estes training · 2024",
    group: "Watch a demonstration",
    note: "Basics, optimization, and troubleshooting; older season rules.",
    href: "https://www.rocketrychallenge.org/resource/estes-education-american-rocketry-challenge-trainings-2024/",
  },
  {
    id: "estes-education-american-rocketry-challenge-trainings-2025",
    title: "Estes training · 2025",
    group: "Watch a demonstration",
    note: "Basics, design, optimization, and flight testing; check current rules.",
    href: "https://www.rocketrychallenge.org/resource/estes-education-american-rocketry-challenge-trainings-2025/",
  },
  {
    id: "events",
    title: "ARC events",
    group: "Team extras",
    note: "Find workshops and season events.",
    href: "https://www.rocketrychallenge.org/events/",
  },
  {
    id: "flight-testing-in-rocket-contest",
    title: "Flight-testing guide",
    group: "Fly and improve",
    note: "How to record flights and find the cause of a miss. Older season examples.",
    href: "https://www.rocketrychallenge.org/wp-content/uploads/Flight-Testing-in-American-Rocketry-Challenge-January-2025.pdf",
  },
  {
    id: "mission-debriefing-rules",
    title: "Mission Debriefing challenge",
    group: "Team extras",
    note: "Explain your design decisions using flight data. Confirm dates with ARC; the printed weekday and date conflict.",
    href: "https://www.rocketrychallenge.org/wp-content/uploads/2027-Mission-Debriefing-Challenge-Rules-2.pdf",
  },
  {
    id: "nar-rocketry-how-to-video-series",
    title: "NAR how-to videos",
    group: "Watch a demonstration",
    note: "Watch basic model-rocketry techniques with your mentor.",
    href: "https://www.rocketrychallenge.org/resource/nar-rocketry-how-to-video-series/",
  },
  {
    id: "parts-of-a-model-rocket",
    title: "ARC component parts · slides",
    group: "Design and build",
    note: "Common parts and suppliers; examples are not a complete legal design.",
    href: "https://www.rocketrychallenge.org/wp-content/uploads/Parts-for-an-ARC-Rocket-July-2026.pptx",
  },
  {
    id: "phone-backgrounds",
    title: "Rocket phone backgrounds",
    group: "Team extras",
    note: "Optional wallpapers from the resource collection.",
    href: "https://www.rocketrychallenge.org/resource/phone-backgrounds/",
  },
  {
    id: "postcards-to-space",
    title: "Postcards to Space",
    group: "Team extras",
    note: "An optional space-themed team activity.",
    href: "https://www.rocketrychallenge.org/postcards-to-space/",
  },
  {
    id: "qualification-flight-form",
    title: "Qualification flight report",
    group: "Fly and improve",
    note: "Use the official form with your NAR observer.",
    href: "https://www.rocketrychallenge.org/wp-content/uploads/Qualification-Flight-Report-for-ARC-2027.pdf",
  },
  {
    id: "rocket-reels-rubric",
    title: "Rocket Reels judging rubric",
    group: "Team extras",
    note: "Check message, creativity, and editing before submitting.",
    href: "https://www.rocketrychallenge.org/wp-content/uploads/2027-Rocket-Reels-Rubric-1.pdf",
  },
  {
    id: "rocket-reels-rules",
    title: "Rocket Reels challenge rules",
    group: "Team extras",
    note: "Video requirements and submission instructions.",
    href: "https://www.rocketrychallenge.org/wp-content/uploads/2027-Rocket-Reels-Challenge-Rules-1.pdf",
  },
  {
    id: "rocketry-starter-kit-2",
    title: "ARC starter kit",
    group: "Start here",
    note: "Useful planning activities. Some targets and dates are outdated; follow the full 2027 rules.",
    href: "https://www.rocketrychallenge.org/wp-content/uploads/2027-ARC-Starter-Kit.pdf",
  },
  {
    id: "so-you-want-to-be-a-rocketeer-video-series",
    title: "So You Want to Be a Rocketeer",
    group: "Watch a demonstration",
    note: "Introductory rocketry video series.",
    href: "https://www.rocketrychallenge.org/resource/so-you-want-to-be-a-rocketeer-video-series/",
  },
  {
    id: "the-american-rocketry-challenge-official-facebook-group",
    title: "ARC community group",
    group: "Team extras",
    note: "A resource for your adult adviser to find team discussions.",
    href: "https://www.rocketrychallenge.org/resource/the-american-rocketry-challenge-official-facebook-group/",
  },
  {
    id: "the-process-of-designing-a-model-rocket",
    title: "Designing a competition rocket",
    group: "Design and build",
    note: "Apogee design process, 2015. Use the design method, not the old targets.",
    href: "https://www.rocketrychallenge.org/wp-content/uploads/Apogee-Newsletter-Tutorial-on-TARC-Design-May-2015.pdf",
  },
  {
    id: "vendor-list",
    title: "ARC vendor list",
    group: "Design and build",
    note: "Find suppliers after checking dimensions and your parts list.",
    href: "https://www.rocketrychallenge.org/resource/vendor-list/",
  },
  {
    id: "nasa-parts",
    title: "NASA: rocket parts",
    group: "Science references",
    note: "Original NASA Glenn explanation and illustration.",
    href: "https://www1.grc.nasa.gov/beginners-guide-to-aeronautics/model-rockets/",
  },
  {
    id: "nasa-stability",
    title: "NASA: stability",
    group: "Science references",
    note: "Original NASA Glenn explanation and illustration.",
    href: "https://www1.grc.nasa.gov/beginners-guide-to-aeronautics/conditions-for-rocket-stability/",
  },
  {
    id: "nasa-flight",
    title: "NASA: a rocket flight",
    group: "Science references",
    note: "Original NASA Glenn explanation and illustration.",
    href: "https://www1.grc.nasa.gov/beginners-guide-to-aeronautics/flight-of-a-model-rocket/",
  },
  {
    id: "nasa-motors",
    title: "NASA: model rocket motors",
    group: "Science references",
    note: "Original NASA Glenn explanation and illustration.",
    href: "https://www1.grc.nasa.gov/beginners-guide-to-aeronautics/model-solid-rocket-engine/",
  },
  {
    id: "nasa-drag",
    title: "NASA: drag and air forces",
    group: "Science references",
    note: "Original NASA Glenn explanation and illustration.",
    href: "https://www1.grc.nasa.gov/beginners-guide-to-aeronautics/rocket-aerodynamics/",
  },
  {
    id: "openrocket",
    title: "OpenRocket: run a simulation",
    group: "Design and build",
    note: "Official walkthrough with screenshots.",
    href: "https://openrocket.readthedocs.io/en/latest/user_guide/basic_flight_simulation.html",
  },
];
