import fs from "node:fs";
import { MODULES } from "../content/modules/registry";
import { SEASON } from "../content/seasons/2027";
import { CITATIONS } from "../content/citations/registry";

// Generates content only; no users, progress, auth settings, or policies.
const quote = (value: string) => "'" + value.replaceAll("'", "''") + "'";
const array = (values: string[]) =>
  "ARRAY[" + values.map(quote).join(",") + "]::text[]";
const lines = [
  "-- Generated by scripts/export-content-sql.ts. Idempotent content catalog only.",
  "begin;",
];
lines.push(
  `insert into public.seasons (year,is_current,parameters,rules_url) values (${SEASON.year},true,${quote(JSON.stringify({ ...SEASON.parameters, constraints: SEASON.constraints, scoring: SEASON.scoring }))}::jsonb,${quote(SEASON.rulesUrl)}) on conflict (year) do update set parameters=excluded.parameters, rules_url=excluded.rules_url;`,
);
for (const m of MODULES) {
  lines.push(
    `insert into public.modules (id,slug,"order",unit,unit_title,title,summary,estimated_minutes,is_timeless,prerequisite_ids,ngss_codes,status,needs_review) values (${[quote(m.id), quote(m.slug), m.order, m.unit, quote(m.unitTitle), quote(m.title), quote(m.summary), m.estimatedMinutes, m.isTimeless, array(m.prerequisiteIds), array(m.ngssCodes), quote(m.status), m.needsReview].join(",")}) on conflict (id) do update set title=excluded.title, summary=excluded.summary, estimated_minutes=excluded.estimated_minutes, status=excluded.status, needs_review=excluded.needs_review;`,
  );
  const dir = String(m.order).padStart(2, "0") + "-" + m.slug;
  lines.push(
    `insert into public.lessons (module_id,mdx_path,needs_review) values (${quote(m.id)},${quote("content/modules/" + dir + "/lesson.mdx")},${m.needsReview}) on conflict (module_id) do update set mdx_path=excluded.mdx_path, needs_review=excluded.needs_review;`,
  );
}
for (const c of Object.values(CITATIONS))
  lines.push(
    `insert into public.citations (id,season,rule_number,topic,quoted_text,source_url,verified_at) values (${[quote(c.id), c.season ?? "null", quote(c.ruleNumber), quote(c.topic), "null", quote(c.sourceUrl), "null"].join(",")}) on conflict (id) do update set season=excluded.season, rule_number=excluded.rule_number, topic=excluded.topic, quoted_text=excluded.quoted_text, source_url=excluded.source_url, verified_at=excluded.verified_at;`,
  );
lines.push("commit;");
fs.writeFileSync("supabase/seed.sql", lines.join("\n\n") + "\n");
console.log("Exported season, module, lesson, and citation catalog.");
